canalroya/urls.py
from django.urls import path
from django.views.generic import RedirectView
from canalroya import views


app_name = 'canalroya'

urlpatterns = [
    path('unirme/', views.TestimonialCreateView.as_view(), name='testimonial-new'),
    path('gracias/', views.TestimonialThanksView.as_view(), name='testimonial-thanks'),
    path('la-voz-de-la-montana/', views.TestimonialListView.as_view(), name='testimonial-list'),
    path('testimonios/<slug:slug>/borrador/', views.TestimonialPreviewView.as_view(), name='testimonial-preview'),
    path('testimonios/<slug:slug>/editar/', views.TestimonialUpdateView.as_view(), name='testimonial-update'),

    path('counter-iframe/', views.CounterIframeView.as_view(), name='counter-iframe'),

    path('aviso-legal/', RedirectView.as_view(
        url='https://elpirineonosevende.org/aviso-legal/'), name='legal-notice'),
    path('politica-de-privacidad/', RedirectView.as_view(
        url='https://elpirineonosevende.org/politica-de-privacidad/'), name='privacy-policy'),
    path('politica-de-cookies/', RedirectView.as_view(
        url='https://elpirineonosevende.org/politica-de-cookies/'), name='cookies-policy'),
]

pdma/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('turberes/', admin.site.urls),
    path('go-home/', RedirectView.as_view(url="https://elpirineonosevende.org/"), name='wp-home'),
]

urlpatterns += i18n_patterns(
    path('', include('canalroya.urls')),
    path('', RedirectView.as_view(pattern_name='canalroya:testimonial-list', permanent=True), name='root_index'),
    prefix_default_language=False,
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

canalroya/models.py
from pathlib import PurePath

from django.db import models
from django.db.models import CharField
from django.db.models.functions import MD5, Cast, Concat
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from canalroya.helpers import get_province_choices


def annotate_ephemeral_slug(queryset):
    """
    Annotate md5 and use it as slug retrieve objects using it
    NOTE: as updated_at is used on md5 link will be expire when
    the object is updated.
    """
    return queryset.annotate(slug=MD5(
        Concat(
            Cast('pk', output_field=CharField()),
            Cast('updated_at', output_field=CharField()),
        )
    ))


def testimonial_image_path(instance, filename):
    filename_extension = PurePath(filename).suffix.lower()
    full_name_slug = slugify(instance.get_full_name())
    prefix = timezone.now().strftime("%Y-%m-%dT%H-%M-%S")
    return f"images/{prefix}-{full_name_slug}{filename_extension}"


class Testimonial(models.Model):
    class Region(models.TextChoices):
        HUESCA = "huesca", "Huesca"
        ZARAGOZA = "zaragoza", "Zaragoza"
        TERUEL = "teruel", "Teruel"
        ARAGON = "aragon", "Aragón"
        OTHER = "otras", "Otras regiones"
        ALL = "", "Todas las regiones"

    class Status(models.IntegerChoices):
        PENDING = 1
        APPROVED = 2
        SPAM = 3
        TRASH = 4
        INCOMPLETE = 5
        DRAFT = 6

    first_name = models.CharField(_('Nombre'), max_length=30)
    last_name = models.CharField(_('Apellidos'), max_length=150)
    email = models.EmailField(_('Correo electrónico'))
    profession = models.CharField(_('Profesión'), max_length=150)
    city = models.CharField(_('Localidad'), max_length=50)
    province = models.CharField(_('Provincia'), max_length=50, choices=get_province_choices())
    comment = models.TextField(_('Comentarios'))
    image = models.ImageField(_('Foto personal (tipo autorretrato)'), upload_to=testimonial_image_path,
                              help_text=(_("Utiliza una foto en la que aparezcas tú. No se aprobarán "
                                           "los testimonios con fotos de paisajes, ni memes, etc.")))

    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)
    status = models.IntegerField(choices=Status.choices, default=Status.PENDING)
    priority = models.PositiveSmallIntegerField(default=100, help_text="Allow define manually testimonial order")

    class Meta:
        indexes = [
            models.Index(fields=['priority', 'created_at'])
        ]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def generate_slug(self):
        from canalroya.utils import annotate_ephemeral_slug
        qs = annotate_ephemeral_slug(Testimonial.objects.filter(pk=self.pk))
        return qs.get().slug

canalroya/forms.py
from typing import Any, Dict

from django import forms
from django.urls import reverse_lazy
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _
from PIL import Image

from canalroya.models import Testimonial


class TestimonialForm(forms.ModelForm):
    IMAGE_WIDTH = 654
    IMAGE_HEIGHT = 490

    comment = forms.CharField(max_length=400, label=_("Comentario"),
                              widget=forms.widgets.Textarea, help_text=_("Máximo 400 carácteres"))
    privacy_policy = forms.BooleanField(required=True, label="Política de privacidad (overrided on __init__)")

    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Testimonial
        fields = ("first_name", "last_name", "email", "profession", "city", "province",
                  "comment", "image", "x", "y", "width", "height")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['privacy_policy'].label = format_html(
            _("He leído y acepto la <a target='_blank' href='{}'>política de privacidad</a> "
              "y declaro que aporto mi testimonio por voluntad propia y con total libertad."),
            reverse_lazy("canalroya:privacy-policy")
        )

    def clean(self) -> Dict[str, Any]:
        cleaned_data = super().clean()
        crop_fields = ["x", "y", "width", "height"]
        if "image" in self.changed_data:
            for fieldname in crop_fields:
                if fieldname not in cleaned_data:
                    self.add_error("image", _("Por favor, recorta la imagen para ajustar su tamaño."))
                    break
        elif self.instance.pk:
            # crop fields are not required because image is not updated
            for fieldname in crop_fields:
                self.errors.pop(fieldname, None)

        return cleaned_data

    def save(self):
        instance = super().save()

        if "image" in self.changed_data:
            x = self.cleaned_data['x']
            y = self.cleaned_data['y']
            w = self.cleaned_data['width']
            h = self.cleaned_data['height']

            image = Image.open(instance.image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((self.IMAGE_WIDTH, self.IMAGE_HEIGHT), Image.ANTIALIAS)
            resized_image.save(instance.image.path)

        return instance

canalroya/views.py
from typing import Any, Dict

from django.conf import settings
from django.contrib.postgres.search import TrigramSimilarity
from django.core.mail import send_mail
from django.db.models import CharField, Q, Value
from django.db.models.functions import Concat
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from canalroya.forms import TestimonialForm
from canalroya.models import Testimonial, annotate_ephemeral_slug


class CanalRoyaContextMixin:
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({
            "ga_id": settings.GOOGLE_ANALYTICS_ID,
        })
        return context


class CounterIframeView(TemplateView):
    template_name = "canalroya/counter_iframe.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["count"] = Testimonial.objects.filter(
            status=Testimonial.Status.APPROVED).count()
        return context


class TestimonialCreateView(CanalRoyaContextMixin, CreateView):
    model = Testimonial
    form_class = TestimonialForm

    def form_valid(self, form):
        form.instance.status = Testimonial.Status.DRAFT
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        path = reverse('canalroya:testimonial-preview', kwargs={"slug": self.object.generate_slug()})
        return path + "#testimonials-content"


class TestimonialPreviewView(CanalRoyaContextMixin, UpdateView):
    model = Testimonial
    fields = ["status"]
    template_name = "canalroya/testimonial_detail.html"
    success_url = reverse_lazy('canalroya:testimonial-thanks')

    def get_queryset(self):
        editable_status = [Testimonial.Status.DRAFT, Testimonial.Status.INCOMPLETE, Testimonial.Status.PENDING]
        qs = Testimonial.objects.filter(status__in=editable_status)
        qs = annotate_ephemeral_slug(qs)
        return qs

    def form_valid(self, form):
        response = super().form_valid(form)
        form.instance.status = Testimonial.Status.PENDING
        form.instance.save()
        self.request.session['testimonial_pk'] = form.instance.pk
        self.send_email_to_user(form.instance)
        return response

    def send_email_to_user(self, instance):
        from_email = settings.DEFAULT_FROM_EMAIL
        to_emails = [instance.email]

        path = reverse_lazy("canalroya:testimonial-preview", kwargs={"slug": instance.generate_slug()})
        url = self.request.build_absolute_uri(path)

        send_mail(
            'Testimonio recibido | El Pirineo no se vende',
            ('Gracias por enviar tu testimonio.\nPuedes ver una vista previa aquí {}\n'
             'Lo revisaremos y aprobaremos lo antes posible.\nPOR FAVOR TEN PACIENCIA.\n\n'
             '#SalvemosCanalRoya'.format(url)),
            from_email,
            to_emails,
            fail_silently=True,
        )


class TestimonialUpdateView(CanalRoyaContextMixin, UpdateView):
    model = Testimonial
    form_class = TestimonialForm

    def get_queryset(self):
        editable_status = [Testimonial.Status.DRAFT, Testimonial.Status.INCOMPLETE, Testimonial.Status.PENDING]
        qs = Testimonial.objects.filter(status__in=editable_status)
        qs = annotate_ephemeral_slug(qs)
        return qs

    def form_valid(self, form):
        form.instance.status = Testimonial.Status.DRAFT
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        path = reverse('canalroya:testimonial-preview', kwargs={"slug": self.object.generate_slug()})
        return path + "#testimonials-content"


class TestimonialThanksView(CanalRoyaContextMixin, TemplateView):
    template_name = "canalroya/testimonial_thanks.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        qs = Testimonial.objects.filter(status=Testimonial.Status.PENDING)
        pk = self.request.session.get('testimonial_pk', None)
        if pk is not None:
            qs = qs.filter(pk__lt=pk)
        context['testimonial_pending_count'] = qs.count()
        return context


class TestimonialListView(CanalRoyaContextMixin, ListView):
    TRIGRAM_MIN_SIMILARITY = 0.23

    model = Testimonial
    paginate_by = 36

    def get_queryset(self):
        qs = Testimonial.objects.filter(status=Testimonial.Status.APPROVED)
        qs = self.search(qs)

        self.region = self.clean_region()
        if self.region:
            if self.region == Testimonial.Region.ARAGON:
                qs = qs.filter(province__in=[
                    Testimonial.Region.HUESCA.label,
                    Testimonial.Region.ZARAGOZA.label,
                    Testimonial.Region.TERUEL.label
                ])
            elif self.region == Testimonial.Region.OTHER:
                qs = qs.exclude(province__in=[
                    Testimonial.Region.HUESCA.label,
                    Testimonial.Region.ZARAGOZA.label,
                    Testimonial.Region.TERUEL.label
                ])
            else:
                qs = qs.filter(province=Testimonial.Region(self.region).label)

        qs = self.sort_queryset(qs)

        return qs

    def search(self, queryset):
        query = self.clean_search_query()
        queryset = queryset.annotate(fullname=Concat('first_name', Value(" "), 'last_name', output_field=CharField()))
        if query:
            qs = queryset.filter(
                Q(fullname__unaccent__icontains=query) |
                Q(city__unaccent__icontains=query)
            )

            if not qs.exists():
                qs = queryset.annotate(similarity=TrigramSimilarity('fullname__unaccent', query))
                qs = qs.filter(similarity__gte=self.TRIGRAM_MIN_SIMILARITY).order_by('-similarity')

            return qs

        return queryset

    def clean_search_query(self):
        q = self.request.GET.get("q", "")
        return q.strip()

    def clean_region(self):
        region = self.request.GET.get("region")
        if region not in Testimonial.Region.values:
            return Testimonial.Region.ALL
        return region

    def sort_queryset(self, qs):
        order_option = self.request.GET.get("o", "")
        if order_option in ["created_at", "-created_at"]:
            order_by = order_option
        elif order_option == "random":
            order_by = "?"
        else:
            # fallback default
            self.sorted_by = "default"
            return qs.order_by("priority", "created_at")

        self.sorted_by = order_option
        return qs.order_by(order_by)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({
            "region_name": Testimonial.Region(self.region).label,
            "sort_options": self.get_sort_options(),
            "sorted_by": self.sorted_by
        })
        return context

    def get_sort_options(self):
        return {
            "created_at": _('Más antiguos') + ' <i class="bi bi-arrow-down"></i>',
            "-created_at": _('Más recientes') + ' <i class="bi bi-arrow-up"></i>',
            "random": _('Orden aleatorio') + ' <i class="bi bi-shuffle"></i>',
        }

canalroya/templates/canalroya/base.html
{% load i18n static %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Testimonios|El Pirineo no se vende</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Avoid index any page of this site -->
  <meta name="robots" content="noindex">

  <!-- Favicons -->
  <link rel="icon" href="{% static 'img/favicon-32.png' %}" sizes="32x32" />
  <link rel="icon" href="{% static 'img/favicon-192.png' %}" sizes="192x192" />
  <link rel="apple-touch-icon" href="{% static 'img/favicon-apple-touch.png' %}" />
  <meta name="msapplication-TileImage" content="{% static 'img/favicon-ms.webp' %}" />

  <!-- Google Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i|Suez+One:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900italic|Oswald:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900italic' rel='stylesheet' />

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- cropper -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/3.1.3/cropper.min.css" />

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- Project CSS File -->
  <link href="{% static 'css/main.css' %}" rel="stylesheet">

  {% block extra_style %}{% endblock %}

  {% if ga_id %}
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id={{ ga_id }}"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '{{ ga_id }}');
  </script>
  {% endif %}
  <!-- =======================================================
  * Template Name: Squadfree - v4.11.0
  * Template URL: https://bootstrapmade.com/squadfree-free-bootstrap-template-creative/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="{{ request.resolver_match.url_name }}">

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-transparent">
    <div class="container d-flex align-items-center justify-content-between position-relative">

      <div class="logo">
        <!-- <h1 class="text-light"><a href="{% url 'canalroya:testimonial-new' %}"><span>El Pirineo no se vende</span></a></h1> -->
        <!-- Uncomment below if you prefer to use an image logo -->
        <a href="{% url 'wp-home'%}">
          <img width="300" height="300" src="{% static 'img/elpirineonosevende-logo.webp' %}" alt="El Pirineo no se vende" class="img-fluid">
        </a>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link" href="{% url 'wp-home'%}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'canalroya:testimonial-new' %}#unirme">{% translate "Unirme" %}</a></li>
          <li><a class="nav-link scrollto" href="{% url 'canalroya:testimonial-list' %}#testimonials">{% translate "Testimonios" %}</a></li>
          {% get_available_languages as languages %}
          {% for lang_code, lang_name in languages %}
            {% language lang_code %}
            <li><a class="nav-link" href="{% url 'root_index' %}">{{ lang_code|upper }}</a></li>
            {% endlanguage %}
          {% endfor %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container" data-aos="fade-up">
      {% block hero %}
      <h1>{% translate "Bienvenido/a" %}</h1>
      <h2>#Salvemoscanalroya</h2>
      <a href="#main" class="btn-get-started scrollto"><i class="bx bx-chevrons-down"></i></a>
      {% endblock %}
    </div>
  </section><!-- End Hero -->

  <main id="main">
    {% block main %}

    {% endblock main %}
  </main><!-- End #main -->

  <!-- ======= Pre-footer ======= -->
  <section id="pre-footer">
    <div class="container">
      <div class="logo mb-3">
        <img class="img-fluid" width="300" height="300" src="{% static 'img/elpirineonosevende-logo.webp' %}" alt="El Pirineo no se vende">
      </div>
      <div class="popular-initiative mb-5">
        <p>
          {% blocktranslate %}
          Esto es una iniciativa popular surgida por WhatsApp entre habitantes de los Pirineos y de participación abierta a
          todo el mundo, de cualquier territorio. No representamos a ningún partido, ni a ninguna asociación ni a ninguna
          plataforma. Nos representamos a nosotros mismos.
          {% endblocktranslate %}
        </p>
        <h2>{% translate "¿TE SUMAS?" %}</h2>
        <a class="btn btn-warning" href="{% url 'canalroya:testimonial-new' %}">{% translate "DEJA TU TESTIMONIO" %} &gt</a>
      </div>

      <div class="social-links mb-4">
        <h2>{% translate "SÍGUENOS EN REDES" %}</h2>
        <div class="icon">
          <a class="" href="https://www.facebook.com/elpirineonosevende/" target="_blank" rel="nofollow"><i class="bi bi-facebook"></i></a>
          <a class="" href="https://www.instagram.com/elpirineonosevende/" target="_blank" rel="nofollow"><i class="bi bi-instagram"></i></a>
          <a class="" href="https://twitter.com/PirineoNoVende" target="_blank" rel="nofollow"><i class="bi bi-twitter"></i></a>
        </div>
      </div>

      <div class="social-share">
        <h3>{% trans "¡COMPARTE LA VOZ<br> DE LA MONTAÑA!" %}</h3>
        <div class="icon">
          <a href="https://www.facebook.com/sharer/sharer.php?u=https://elpirineonosevende.org/" target="_blank" rel="nofollow noopener"><i class="bi bi-facebook"></i></a>
          <a href="https://twitter.com/intent/tweet?url=https://elpirineonosevende.org/&text=#SalvemosCanalRoya&via=" target="_blank" rel="nofollow noopener"><i class="bi bi-twitter"></i></a>
          <a href="https://api.whatsapp.com/send?text=#SalvemosCanalRoya%20https://elpirineonosevende.org" target="_blank" rel="nofollow noopener"><i class="bi bi-whatsapp"></i></a>
          <a href="https://telegram.me/share/url?url=https://elpirineonosevende.org/&text=#SalvemosCanalRoya" target="_blank" rel="nofollow noopener"><i class="bi bi-telegram"></i></a>
          <a href="mailto:?subject=#SalvemosCanalRoya&body=https://elpirineonosevende.org/" target="_blank" rel="nofollow noopener"><i class="bi bi-envelope"></i></a>
        </div>
      </div>
    </div>
  </section><!-- End Pre-footer -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">

      <div class="copyright">
        {% blocktranslate %}
        Gracias a todos/as los/as amigos/as que han animado el hombro para sacar esto adelante y a toda la gente que, sin
        pensarlo, ha ofrecido su testimonio para lanzar el proyecto.
        {% endblocktranslate %}
      </div>

      <div class="text-center mt-3">
        {% trans "NOTA: Si una vez enviado tu testimonio quieres eliminarlo escríbenos a" %}
        <a href="mailto:testimonios@elpirineonosevende.org">testimonios@elpirineonosevende.org</a>
      </div>

      <div class="credits mt-3 mb-5">
        {% trans "Diseño" %} <a href="https://garabatoestudio.com" rel="external nofollow noopener" target="_blank">Garabato Estudio</a> /
        {% trans "Desarrollo" %} <a href="https://santiagolamora.com" rel="external nofollow noopener" target="_blank">Ribaguifi</a>
      </div>

      <div class="w-50 mx-auto mt-4" style="background-color: #ababab; height: 1px"></div>
      <div class="credits mt-2">
        <ul class="nav justify-content-center">
          <li class="nav-item"><a class="nav-link" href="{% url 'canalroya:legal-notice' %}">{% trans "Aviso legal" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'canalroya:privacy-policy' %}">{% trans "Política de Privacidad" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'canalroya:cookies-policy' %}">{% trans "Política de Cookies" %}</a></li>
        </ul>
      </div>

    </div>
  </footer><!-- End Footer -->

  <!-- ======= Post-footer ======= -->
  <section id="post-footer">
    <div class="container">
      <h6 class="heading-title">{% trans "Si quieres ayudar más a la Canal Roya, contacta con Asamblea Canal Roya" %}</h6>
      <a href="https://asambleacanalroya.org/" target="_blank" rel="nofollow">
        <img class="logo-asamblea" width="300" height="300"
          src="{% static 'img/asamblea-canalroya-logo.webp' %}"
          alt="Logo Asamblea Canal Roya" loading="lazy"> </a>
    </div>
  </section>

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  <!-- cropperjs -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/3.1.3/cropper.min.js"></script>


  {% block extra_script %}{% endblock %}
</body>

</html>

canalroya/templates/canalroya/testimonial_pagination.html
{% load paginator_tags %}

<nav class="w-auto" aria-label="Navegación por las diferentes páginas">
  <ul class="pagination">
    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
      <a class="page-link" aria-label="Anterior"
        href="{% if page_obj.has_previous %}?{% url_replace page=page_obj.previous_page_number %}{% endif %}#testimonials-content">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>

    {% get_proper_elided_page_range page_obj.paginator page_obj.number as page_range %}
    {% for i in page_range %}
      {% if page_obj.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }}</span></li>
      {% else %}
        {% if i == page_obj.paginator.ELLIPSIS %}
          <li class="page-item"><span class="page-link">{{ page_obj.paginator.ELLIPSIS }}</span></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?{% url_replace page=i %}#testimonials-content">{{ i }}</a></li>
        {% endif %}
      {% endif %}
    {% endfor %}

    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
      <a class="page-link" aria-label="Siguiente"
        href="{% if page_obj.has_next %}?{% url_replace page=page_obj.next_page_number %}{% endif %}#testimonials-content">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>